[package]
name = "serialization"
version.workspace = true  
edition.workspace = true
author.workspace = true 
description.workspace = true
repository.workspace = true 
license.workspace = true
keywords = ["serialization"]
readme = "./README.md"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[workspace]
members = ["impl", "serialization_minecraft", "serialization_nbt"]

[workspace.package]
version = "0.2.1"
description = "encode and decode your struct"
edition = "2021"
author = "Bruce0203 <brucefreedy@gmail.com>"
repository = "https://github.com/Bruce0203/serialization"
license = "MIT"

[dependencies]
serialization_derive = { path = "./impl", version = "0.2.1" }
fastbuf = "0.28.0"
seq-macro = "0.3"
concat-idents-bruce0203 = "1.1.6"
arrayvec = { version = "0.7.6", optional = true }
uuid = { version = "1.11.0", optional = true }
fastvarint = { version = "0.22.0", optional = true }
nonmax = { version = "0.5.5", optional = true }
constvec = "0.1.8"

[dev-dependencies]
divan = "0.1.17"
serialization_minecraft = { path = "./serialization_minecraft" }

[features]
default = ["std", "arrayvec", "fastvarint", "uuid", "nonmax", ]
std = []
uuid = ["dep:uuid", "serialization_derive/uuid"]
arrayvec = ["dep:arrayvec", "serialization_derive/arrayvec"]
fastvarint = ["dep:fastvarint", "serialization_derive/fastvarint"]
nonmax = ["dep:nonmax"]
fast_binary_format = ["serialization_derive/fast_binary_format"]

[[bench]]
name = "sandbox"
harness = false


