#![feature(core_intrinsics)]
#![feature(fmt_helpers_for_derive)]
#![feature(derive_eq)]
#![feature(structural_match)]
#![feature(coverage_attribute)]
#![feature(panic_internals)]
#![feature(rustc_attrs)]
#![feature(print_internals)]
