name: bench
on:
  workflow_dispatch:
  push:
    #    branches:
    #      - main

env:
  RUST_MSRV: "1.83"

jobs:
  deploy:
    name: bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Repo MSRV toolchain
        run: |
          sudo apt-get install valgrind
          cargo -V
      - name: Run 
        run: |
          cargo bench

 
