name: bench
on:
  workflow_dispatch:
  push:
    #    branches:
    #      - main

env:
  RUST_MSRV: "1.83"

jobs:
  deploy:
    name: bench
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Install Repo MSRV toolchain
        run: |
          cargo -V
      - uses: taiki-e/install-action@cargo-binstall
      - name: Install iai-callgrind-runner
        run: |
          sudo apt-get install valgrind
          version=$(cargo metadata --format-version=1 |\
            jq '.packages[] | select(.name == "iai-callgrind").version' |\
            tr -d '"'
          )
          cargo binstall --no-confirm iai-callgrind-runner --version $version
      - name: Run 
        run: |
          cargo bench

 
